name: RegionDBD
version: 1.0
main: br.com.dvlopando.regionbdb.RegionBDB
commands:
  epccreate:
    description: Gerenciar Plugin
    usage: /epccreate
  epcaddregion:
    description: Create a new epc region
    usage: /epcaddregion